server:
  port: 8083

spring:
  jackson:
    default-property-inclusion: non_null

#spring:
#  application:
#    name: authorization-service
#  config:
#    import: optional:configserver:http://localhost:8888
##  cloud:
##    config:
##      uri: http://localhost:8888  # Pointing to your config-service
##  sleuth:
##    sampler:
##      probability: 1.0
##  zipkin:
##    base-url: http://localhost:9411/

# Eureka settings
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS}:${EUREKA_PORT}/eureka/

  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      management.port: ${management.server.port:${server.port}}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

  endpoint:
    prometheus:
      access: read_only
    health:
      show-details: always
      show-components: always

  metrics:
    enable:
      cache: true


resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
