spring.application.name=portal-onboard-service


spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/gridflex-DB?ApplicationName=portal-onboard-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.postgresql=DEBUG

spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB