spring.application.name=portal-onboard-service

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ApplicationName=portal-onboard-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#logging.level.org.postgresql=DEBUG

file.upload-dir=/${LOCATION}/uploads

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_USERNAME}

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.leak-detection-threshold=20000

logging.level.org.springframework.cloud.gateway=DEBUG
logging.file.name: /${LOCATION}/logs/portal.log

logging.logback.rollingpolicy=max-file-size=20MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.file-name-pattern: /${LOCATION}/logs/portal.%d{yyyy-MM-dd}.%i.log