spring.application.name=portal-onboard-service

spring.datasource.url=jdbc:postgresql://localhost:8432/gridflexdb?ApplicationName=portal-onboard-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.postgresql=DEBUG

spring.data.mongodb.uri=mongodb://localhost:27017/Audit-Notification-DB

#-----------
#spring.datasource.url=jdbc:postgresql://localhost:8432/gridflexdb?ApplicationName=gridflex-backend-service
#spring.datasource.username=postgres
#spring.datasource.password=Passw0rd0405&
#spring.datasource.driver-class-name=org.postgresql.Driver
#
##?connectTimeout=10&sslmode=prefer
#spring.data.mongodb.uri=mongodb://localhost:27017/Audit-Notification-DB

## HikariCP settings
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000
#
#spring.datasource.hikari.leak-detection-threshold=20000


# Timezone setting
#spring.jackson.time-zone=Africa/Lagos
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#spring.datasource.hikari.data-source-properties.applicationName=portal-onboard-service

#
#
## Show SQL statements
#spring.jpa.show-sql=true
#
## Format SQL logs
#spring.jpa.properties.hibernate.format_sql=true
#
## Log transaction boundaries (commit/rollback)
#logging.level.org.springframework.transaction=DEBUG
#
## Log when connections are taken/released from the pool
#logging.level.com.zaxxer.hikari=DEBUG
#
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
#
#file.upload-dir=/opt/java-webservices/uploads
##file.upload-dir = C:/Users/H.Soliu/Documents/Memmcol-project/uploads
#
## Properties
#success.code = 000
#fail.code = 013
#token.code = 001
#reg.code = 010
#payload.code = 011
#block.code = 012
#update.code = 020
#del.code = 030
#get.code = 040
#exist.code = 050
#notfound.code = 060
#token.notfound.code = 061
#role.code = 070
#role.del.code = 080
#role.update.code = 090
#
## Descriptions
#payload.desc = Bad Request
#success.desc = Successful
#fail.desc = Unsuccessfully
#token.desc = Authentication Successful
#token.notfound.desc = Authorization Token Not Found
#reg.desc = Registered Successfully
#notfound.desc = Not Found
#update.desc = Updated Successfully
#del.desc = Deactivated Successfully
#get.desc = Fetched Successfully
#exist.desc = Already Exist
#
#block.fail.desc = Blocked Unsuccessfully
#reg.fail.desc = Registration Unsuccessfully
#update.fail.desc = Update Unsuccessfully
#del.fail.desc = Disabled Unsuccessfully
#get.fail.desc = Fetching Unsuccessfully
#
#hazelcast.instance-name = portalAuthInstance
#hazelcast.cluster-name = portalAuthCluster
#hazelcast.network.port = 5702
#hazelcast.network.join.multicast.enabled = true
#hazelcast.time-to-live-seconds = 86400
#hazelcast.max-size = 1000
#hazelcast-max-idle-seconds = 18000
#hazelcast-in-memory-format = OBJECT
#hazelcast-invalidate-on-change = true
#hazelcast-max-size-policy = ENTRY_COUNT
#hazelcast-eviction-policy = LFU
#hazelcast-cache-local-entries = false
#hazelcast-enabled = true
#hazelcast-directory = portalNearCacheDev
#hazelcast-store-initial-delay-seconds = 300
#hazelcast-store-interval-seconds = 600
#hazelcast-local-update-policy = INVALIDATE
#hazelcast-local-entries = true
#hazelcast-serialize-key = true



