--CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- Seed initial operator with roles
-- UUID is generated by PostgreSQL (gen_random_uuid)

WITH new_operator AS (
INSERT INTO portal_users (
    firstname,
    lastname,
    department,
    email,
    phone_no,
    password,
    status,
    active,
    created_at,
    updated_at
)
SELECT
    'R&D',
    'Software',
    'R&D Software',
    'memmcolapp@gmail.com',
    '+2348012345678',
    '$2a$10$vpdTuh9gul9V3YTye2DNXeKOz4QKU1JFssIgcXm0YSrn.ySonEnrO',
    TRUE,
    TRUE,
    NOW(),
    NOW()
    WHERE NOT EXISTS (
        SELECT 1 FROM portal_users WHERE email = 'memmcolapp@gmail.com'
    )
    RETURNING id
)
INSERT INTO portal_roles (user_id, user_role)
SELECT id, role
FROM new_operator,
     UNNEST(ARRAY['SUPER_ADMIN']) AS role(role);

